### PR TITLE
HowToUseTaskmailBot

### LINKED ISSUE #107: Create a How to use Taskmail Bot md file for instructions
Create an HowToUseTaskmailBot.md file to list out instructions on how to use Taskmail Bot.

### PR DESCRIPTION
**Pull request by siddharthashw**
Fixed #107 
**File changed:**
**1. HowToUseTaskmailBot.md** - Added instruction to use task mail bot

### CODE REVIEW

**Review by chintans — CHANGES_REQUESTED** [review]
written instruction is not enough to understand what task mail bot does. Additionally, instructions are grammatically incorrect. Instructions lack proper formatting too.

**Comment by siddharthashw** [comment]
Added more lines for better understanding of task mail working

**Review by chintans — CHANGES_REQUESTED** [review]
Grammatical mistakes are there. Please correct them.

**Comment by siddharthashw** [comment]
Rectified all grammatical error by using **"grammarly"**

**Review by chintans — APPROVED** [review]

**Pull request merged**
